-- ===========================================================================
-- Sistema de Administración de Referencias (SAR)
-- Script de Migración Incremental: Control de Inventario
-- Archivo: scripts/migration_inventario_v1.sql
-- ===========================================================================

-- 1. Eliminar la antigua tabla vacía e inutilizada de asignación
DROP TABLE IF EXISTS sar_archivo.asignacion CASCADE;

-- 2. Crear Catálogo de Notarías
CREATE TABLE IF NOT EXISTS sar_catalogo.notaria (
    notaria_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(200) NOT NULL UNIQUE,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 3. Crear Catálogo de Colaboradores
CREATE TABLE IF NOT EXISTS sar_catalogo.colaborador (
    colaborador_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(200) NOT NULL UNIQUE,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 4. Crear Catálogo de Desarrollos (Vinculado a Delegación)
CREATE TABLE IF NOT EXISTS sar_catalogo.desarrollo (
    desarrollo_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    delegacion_id BIGINT NOT NULL,
    nombre VARCHAR(200) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (delegacion_id) REFERENCES sar_catalogo.delegacion(delegacion_id) ON DELETE RESTRICT,
    CONSTRAINT uq_desarrollo_delegacion UNIQUE (nombre, delegacion_id)
);

-- 5. Crear Tabla Maestra de Asignación de Lotes
CREATE TABLE IF NOT EXISTS sar_archivo.lote_asignacion (
    lote_asignacion_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_destino VARCHAR(20) NOT NULL, -- 'NOTARIA' o 'COLABORADOR'
    notaria_id BIGINT,
    colaborador_id BIGINT,
    solicitante_externo VARCHAR(200), -- Persona física que solicita (ej. Pedro Gómez)
    fecha TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    observaciones TEXT,
    usuario_creacion BIGINT NOT NULL,
    FOREIGN KEY (notaria_id) REFERENCES sar_catalogo.notaria(notaria_id) ON DELETE RESTRICT,
    FOREIGN KEY (colaborador_id) REFERENCES sar_catalogo.colaborador(colaborador_id) ON DELETE RESTRICT,
    FOREIGN KEY (usuario_creacion) REFERENCES sar_seguridad.usuario(usuario_id) ON DELETE RESTRICT
);

-- 6. Crear Tabla Detalle de Asignación (Desagregado por Referencia)
CREATE TABLE IF NOT EXISTS sar_archivo.lote_detalle (
    lote_detalle_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lote_asignacion_id BIGINT NOT NULL,
    cliente VARCHAR(250) NOT NULL,
    desarrollo_id BIGINT NOT NULL,
    fecha_solicitud DATE,
    mz VARCHAR(50),
    lote VARCHAR(50),
    edif VARCHAR(50),
    viv VARCHAR(50),
    folio_electronico VARCHAR(100),
    estatus_primer_aviso VARCHAR(100),
    concepto_solicitado VARCHAR(50) NOT NULL,
    referencia_id BIGINT,
    referencia_asignada VARCHAR(100) NOT NULL UNIQUE,
    FOREIGN KEY (lote_asignacion_id) REFERENCES sar_archivo.lote_asignacion(lote_asignacion_id) ON DELETE CASCADE,
    FOREIGN KEY (desarrollo_id) REFERENCES sar_catalogo.desarrollo(desarrollo_id) ON DELETE RESTRICT,
    FOREIGN KEY (referencia_id) REFERENCES sar_produccion.referencia(referencia_id) ON DELETE SET NULL
);

-- Índices de rendimiento
CREATE INDEX IF NOT EXISTS idx_lote_detalle_ref_id ON sar_archivo.lote_detalle (referencia_id);
CREATE INDEX IF NOT EXISTS idx_lote_detalle_cliente ON sar_archivo.lote_detalle (cliente);
CREATE INDEX IF NOT EXISTS idx_lote_detalle_desarrollo ON sar_archivo.lote_detalle (desarrollo_id);
CREATE INDEX IF NOT EXISTS idx_lote_asignacion_destino ON sar_archivo.lote_asignacion (tipo_destino);

-- Semilla de Notarías de prueba
INSERT INTO sar_catalogo.notaria (nombre) VALUES 
('Notaría 12'), ('Notaría 15'), ('Notaría 5') 
ON CONFLICT (nombre) DO NOTHING;
