"""Migration script to safely convert SERIAL columns to IDENTITY, add RFC constraints, and add performance indexes without data loss."""

import sys
import os
from sqlalchemy import text

# Ensure root dir is in path
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..")))

from sar.src.storage.db_connector import DatabaseConnector

TABLES_TO_MIGRATE = [
    ("sar_seguridad.usuario", "usuario_id"),
    ("sar_seguridad.rol", "rol_id"),
    ("sar_seguridad.app_modulo", "app_modulo_id"),
    ("sar_seguridad.modulo", "modulo_id"),
    ("sar_seguridad.accion", "accion_id"),
    ("sar_seguridad.permiso", "permiso_id"),
    ("sar_seguridad.sesion", "sesion_id"),
    
    ("sar_catalogo.municipio", "municipio_id"),
    ("sar_catalogo.delegacion", "delegacion_id"),
    ("sar_catalogo.concepto", "concepto_id"),
    ("sar_catalogo.rfc", "rfc_id"),
    ("sar_catalogo.estado_sistema", "estado_id"),
    ("sar_catalogo.evento_sistema", "evento_id"),
    
    ("sar_produccion.orden_generacion", "orden_id"),
    ("sar_produccion.grupo_referencia", "grupo_id"),
    ("sar_produccion.solicitud", "solicitud_id"),
    ("sar_produccion.referencia", "referencia_id"),
    
    ("sar_archivo.archivo_pdf", "archivo_id"),
    ("sar_archivo.factura", "factura_id"),
    
    ("sar_auditoria.auditoria_login", "login_id"),
    ("sar_auditoria.auditoria_evento", "evento_auditoria_id"),
    ("sar_auditoria.auditoria_error", "error_id"),
    
    ("sar_configuracion.parametro_sistema", "parametro_id"),
    ("sar_configuracion.localizador_portal", "localizador_id"),
]

def run_migration():
    print("Iniciando migración segura de base de datos física PostgreSQL...")
    db = DatabaseConnector()
    
    try:
        with db.get_session() as session:
            # 1. Migrar SERIAL a IDENTITY
            for table_fullname, col_name in TABLES_TO_MIGRATE:
                schema_name, table_name = table_fullname.split(".")
                
                # Check if it is already an identity column
                check_identity_query = text(f"""
                    SELECT is_identity 
                    FROM information_schema.columns 
                    WHERE table_schema = :schema 
                      AND table_name = :table 
                      AND column_name = :column;
                """)
                is_identity = session.execute(check_identity_query, {
                    "schema": schema_name, 
                    "table": table_name, 
                    "column": col_name
                }).scalar()
                
                if is_identity == "YES":
                    print(f"[INFO] {table_fullname}.{col_name} ya es columna IDENTITY. Saltando...")
                else:
                    print(f"[MIGRANDO] Convirtiendo {table_fullname}.{col_name} de SERIAL a IDENTITY...")
                    # Alter columns
                    alter_query = text(f"""
                        ALTER TABLE {table_fullname} ALTER COLUMN {col_name} DROP DEFAULT;
                        ALTER TABLE {table_fullname} ALTER COLUMN {col_name} ADD GENERATED BY DEFAULT AS IDENTITY;
                    """)
                    session.execute(alter_query)
                    
                    # Sync sequence val
                    sync_query = text(f"""
                        SELECT setval(
                            COALESCE(pg_get_serial_sequence('{table_fullname}', '{col_name}'), '{table_fullname}_{col_name}_seq'), 
                            COALESCE((SELECT MAX({col_name}) FROM {table_fullname}), 0) + 1, 
                            false
                        );
                    """)
                    session.execute(sync_query)
                    print(f"[OK] {table_fullname}.{col_name} convertida con éxito.")
            
            # 2. Agregar restricción CHECK a sar_catalogo.rfc si no existe
            check_constraint_query = text("""
                SELECT COUNT(*) 
                FROM information_schema.table_constraints 
                WHERE table_schema = 'sar_catalogo' 
                  AND table_name = 'rfc' 
                  AND constraint_name = 'chk_rfc_pattern';
            """)
            constraint_exists = session.execute(check_constraint_query).scalar()
            
            if constraint_exists == 0:
                print("[MIGRANDO] Añadiendo restricción CHECK 'chk_rfc_pattern' a sar_catalogo.rfc...")
                # Primero, verificar si hay algún RFC inválido actualmente para no fallar
                invalid_rfcs_query = text("""
                    SELECT rfc FROM sar_catalogo.rfc WHERE NOT (rfc ~* '^[A-Z&Ññ]{3,4}[0-9]{6}[A-Z0-9]{3}$');
                """)
                invalid_rfcs = session.execute(invalid_rfcs_query).fetchall()
                if invalid_rfcs:
                    print(f"[ADVERTENCIA] Hay RFCs en la base de datos que no cumplen el formato: {[r[0] for r in invalid_rfcs]}")
                    print("[INFO] Saltando la restricción CHECK para evitar fallos de integridad con datos inválidos existentes.")
                else:
                    alter_rfc_query = text("""
                        ALTER TABLE sar_catalogo.rfc 
                        ADD CONSTRAINT chk_rfc_pattern 
                        CHECK (rfc ~* '^[A-Z&Ññ]{3,4}[0-9]{6}[A-Z0-9]{3}$');
                    """)
                    session.execute(alter_rfc_query)
                    print("[OK] Restricción CHECK 'chk_rfc_pattern' aplicada exitosamente.")
            else:
                print("[INFO] La restricción CHECK 'chk_rfc_pattern' ya existe. Saltando...")
            
            # 3. Agregar los índices de optimización adicionales
            print("[MIGRANDO] Creando índices adicionales de rendimiento...")
            indexes_queries = [
                "CREATE INDEX IF NOT EXISTS idx_factura_rfc_emisor ON sar_archivo.factura (rfc_emisor);",
                "CREATE INDEX IF NOT EXISTS idx_factura_fecha_factura ON sar_archivo.factura (fecha_factura DESC);",
                "CREATE INDEX IF NOT EXISTS idx_referencia_fecha_vigencia ON sar_produccion.referencia (fecha_vigencia);",
                "CREATE INDEX IF NOT EXISTS idx_asignacion_usuario_destino ON sar_archivo.asignacion (usuario_destino);"
            ]
            for query in indexes_queries:
                session.execute(text(query))
            print("[OK] Índices de rendimiento creados exitosamente.")
            
            session.commit()
            print("¡MIGRACIÓN EXITOSA! Todos los cambios se aplicaron conservando los datos existentes.")
            
    except Exception as e:
        print(f"[ERROR CRÍTICO] La migración falló: {str(e)}")

if __name__ == "__main__":
    run_migration()
