-- ============================================================================
-- SAR - CONTROL DE INVENTARIO Y ASIGNACIÓN DE REFERENCIAS
-- ============================================================================
-- Tablas:
--   1. sar_archivo.lote_asignacion
--   2. sar_archivo.ubicacion
--   3. sar_archivo.asignacion_referencia
--
-- Flujo:
--
--   LOTE_ASIGNACION
--          │
--          ▼
--   ASIGNACION_REFERENCIA
--          │
--          ├── REFERENCIA
--          │
--          └── UBICACION (NULL mientras la notaría no confirme)
--
-- Esto permite:
--
--   1. Reservar referencias anticipadamente.
--   2. Crear el lote sin conocer todavía cliente/ubicación.
--   3. Posteriormente asociar cada referencia con una ubicación.
--   4. Registrar múltiples intentos para una misma ubicación/concepto.
-- ============================================================================


-- ============================================================================
-- 1. TABLA: lote_asignacion
-- ============================================================================
-- Representa la operación mediante la cual se reserva/asigna un conjunto
-- de referencias a una notaría o colaborador.
--
-- La ubicación NO se registra aquí porque puede ser desconocida al momento
-- de crear el lote.
-- ============================================================================

CREATE TABLE sar_archivo.lote_asignacion (
    lote_asignacion_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    tipo_destino VARCHAR(20) NOT NULL,

    notaria_id BIGINT,

    colaborador_id BIGINT,

    solicitante_externo VARCHAR(200),

    fecha TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    observaciones TEXT,

    usuario_creacion BIGINT NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- ------------------------------------------------------------------------
    -- FOREIGN KEYS
    -- ------------------------------------------------------------------------

    CONSTRAINT fk_lote_asignacion_notaria
        FOREIGN KEY (notaria_id)
        REFERENCES sar_catalogo.notaria(notaria_id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_lote_asignacion_colaborador
        FOREIGN KEY (colaborador_id)
        REFERENCES sar_catalogo.colaborador(colaborador_id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_lote_asignacion_usuario
        FOREIGN KEY (usuario_creacion)
        REFERENCES sar_seguridad.usuario(usuario_id)
        ON DELETE RESTRICT,

    -- ------------------------------------------------------------------------
    -- VALIDACIONES
    -- ------------------------------------------------------------------------

    CONSTRAINT chk_lote_asignacion_tipo_destino
        CHECK (
            tipo_destino IN ('NOTARIA', 'COLABORADOR')
        ),

    CONSTRAINT chk_lote_asignacion_destino
        CHECK (
            (
                tipo_destino = 'NOTARIA'
                AND notaria_id IS NOT NULL
                AND colaborador_id IS NULL
            )
            OR
            (
                tipo_destino = 'COLABORADOR'
                AND colaborador_id IS NOT NULL
                AND notaria_id IS NULL
            )
        )
);


-- ============================================================================
-- 2. TABLA: ubicacion
-- ============================================================================
-- Representa los datos del cliente/inmueble/trámite.
--
-- IMPORTANTE:
-- Esta tabla NO depende de lote_asignacion.
--
-- Una misma ubicación puede recibir referencias en diferentes momentos,
-- lotes o intentos.
-- ============================================================================

CREATE TABLE sar_archivo.ubicacion (
    ubicacion_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    cliente VARCHAR(250) NOT NULL,

    desarrollo_id BIGINT NOT NULL,

    fecha_solicitud DATE,

    sm VARCHAR(50),

    mz VARCHAR(50),

    lote VARCHAR(50),

    edif VARCHAR(50),

    viv VARCHAR(50),

    credito_titular VARCHAR(250),

    delegacion VARCHAR(100),

    lote_id_erp VARCHAR(100),

    comentarios TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- ------------------------------------------------------------------------
    -- FOREIGN KEYS
    -- ------------------------------------------------------------------------

    CONSTRAINT fk_ubicacion_desarrollo
        FOREIGN KEY (desarrollo_id)
        REFERENCES sar_catalogo.desarrollo(desarrollo_id)
        ON DELETE RESTRICT
);


-- ============================================================================
-- 3. TABLA: lote_detalle
-- ============================================================================
-- Representa la solicitud agrupada (renglón) capturada en una orden/lote.
-- Define la demanda de referencias solicitadas para una empresa/concepto/desarrollo.
-- ============================================================================

CREATE TABLE sar_archivo.lote_detalle (
    lote_detalle_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    lote_asignacion_id BIGINT NOT NULL,

    rfc_id BIGINT NOT NULL,

    concepto_id BIGINT NOT NULL,

    desarrollo_id BIGINT NOT NULL,

    cantidad_solicitada INTEGER NOT NULL,

    cantidad_confirmada INTEGER NOT NULL DEFAULT 0,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- ------------------------------------------------------------------------
    -- FOREIGN KEYS
    -- ------------------------------------------------------------------------

    CONSTRAINT fk_lote_detalle_lote
        FOREIGN KEY (lote_asignacion_id)
        REFERENCES sar_archivo.lote_asignacion(lote_asignacion_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_lote_detalle_rfc
        FOREIGN KEY (rfc_id)
        REFERENCES sar_catalogo.rfc(rfc_id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_lote_detalle_concepto
        FOREIGN KEY (concepto_id)
        REFERENCES sar_catalogo.concepto(concepto_id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_lote_detalle_desarrollo
        FOREIGN KEY (desarrollo_id)
        REFERENCES sar_catalogo.desarrollo(desarrollo_id)
        ON DELETE RESTRICT
);


-- ============================================================================
-- 4. TABLA: asignacion_referencia
-- ============================================================================
-- Representa cada factura/referencia física individual vinculada a un renglón
-- del lote. Si la notaría aún no la concilia con un cliente, ubicacion_id es NULL.
-- ============================================================================

CREATE TABLE sar_archivo.asignacion_referencia (
    asignacion_referencia_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    lote_detalle_id BIGINT NOT NULL,

    referencia_id BIGINT NOT NULL,

    ubicacion_id BIGINT,

    intento INTEGER NOT NULL DEFAULT 1,

    estado_id BIGINT NOT NULL,

    fecha_asignacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    usuario_asignacion BIGINT NOT NULL,

    fecha_confirmacion TIMESTAMPTZ,

    usuario_confirmacion BIGINT,

    observaciones TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- ------------------------------------------------------------------------
    -- FOREIGN KEYS
    -- ------------------------------------------------------------------------

    CONSTRAINT fk_asignacion_referencia_detalle
        FOREIGN KEY (lote_detalle_id)
        REFERENCES sar_archivo.lote_detalle(lote_detalle_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_asignacion_referencia_referencia
        FOREIGN KEY (referencia_id)
        REFERENCES sar_produccion.referencia(referencia_id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_asignacion_referencia_ubicacion
        FOREIGN KEY (ubicacion_id)
        REFERENCES sar_archivo.ubicacion(ubicacion_id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_asignacion_referencia_estado
        FOREIGN KEY (estado_id)
        REFERENCES sar_catalogo.estado_sistema(estado_id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_asignacion_referencia_usuario
        FOREIGN KEY (usuario_asignacion)
        REFERENCES sar_seguridad.usuario(usuario_id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_asignacion_referencia_usuario_confirmacion
        FOREIGN KEY (usuario_confirmacion)
        REFERENCES sar_seguridad.usuario(usuario_id)
        ON DELETE RESTRICT,

    -- ------------------------------------------------------------------------
    -- VALIDACIONES
    -- ------------------------------------------------------------------------

    CONSTRAINT chk_asignacion_referencia_intento
        CHECK (intento >= 1),

    CONSTRAINT chk_asignacion_referencia_confirmacion
        CHECK (
            (
                fecha_confirmacion IS NULL
                AND usuario_confirmacion IS NULL
            )
            OR
            (
                fecha_confirmacion IS NOT NULL
                AND usuario_confirmacion IS NOT NULL
            )
        ),

    -- ------------------------------------------------------------------------
    -- UN INTENTO POR RENGLÓN Y UBICACIÓN
    -- ------------------------------------------------------------------------

    CONSTRAINT uq_ubicacion_lote_detalle_intento
        UNIQUE (
            ubicacion_id,
            lote_detalle_id,
            intento
        ),

    -- ------------------------------------------------------------------------
    -- UNA REFERENCIA NO PUEDE SER ASIGNADA A DOS OPERACIONES
    -- ------------------------------------------------------------------------

    CONSTRAINT uq_asignacion_referencia_referencia
        UNIQUE (referencia_id)
);


-- ============================================================================
-- ÍNDICES
-- ============================================================================


-- ============================================================================
-- LOTE_ASIGNACION
-- ============================================================================

CREATE INDEX idx_lote_asignacion_notaria
    ON sar_archivo.lote_asignacion (notaria_id);

CREATE INDEX idx_lote_asignacion_colaborador
    ON sar_archivo.lote_asignacion (colaborador_id);

CREATE INDEX idx_lote_asignacion_fecha
    ON sar_archivo.lote_asignacion (fecha);

CREATE INDEX idx_lote_asignacion_usuario
    ON sar_archivo.lote_asignacion (usuario_creacion);


-- ============================================================================
-- LOTE_DETALLE
-- ============================================================================

CREATE INDEX idx_lote_detalle_lote
    ON sar_archivo.lote_detalle (lote_asignacion_id);


-- ============================================================================
-- UBICACION
-- ============================================================================

CREATE INDEX idx_ubicacion_desarrollo
    ON sar_archivo.ubicacion (desarrollo_id);


-- ============================================================================
-- ASIGNACION_REFERENCIA
-- ============================================================================

CREATE INDEX idx_asignacion_referencia_detalle
    ON sar_archivo.asignacion_referencia (lote_detalle_id);

CREATE INDEX idx_asignacion_referencia_ubicacion
    ON sar_archivo.asignacion_referencia (ubicacion_id);

CREATE INDEX idx_asignacion_referencia_referencia
    ON sar_archivo.asignacion_referencia (referencia_id);

CREATE INDEX idx_asignacion_referencia_estado
    ON sar_archivo.asignacion_referencia (estado_id);

CREATE INDEX idx_asignacion_referencia_usuario
    ON sar_archivo.asignacion_referencia (usuario_asignacion);


-- ============================================================================
-- CONSULTA PRINCIPAL DEL HISTORIAL DE UNA UBICACIÓN
-- ============================================================================
-- Este índice permite obtener rápidamente todos los intentos de una ubicación
-- ordenados por fecha.
-- ============================================================================

CREATE INDEX idx_asignacion_ubicacion_fecha
    ON sar_archivo.asignacion_referencia (
        ubicacion_id,
        fecha_asignacion DESC
    );


-- ============================================================================
-- FIN DEL SCRIPT
-- ============================================================================