-- ===========================================================================
-- Sistema de Administración de Referencias (SAR) + CancunBot
-- Script de Creación Física de Base de Datos para PostgreSQL 18+
-- Archivo: sar_db.sql
-- Versión: 3.0 — Fuente de la Verdad (sincronizada con producción 2026-08-20)
-- ===========================================================================
-- Cambios v3.0:
--   - Sincronizado contra dump de producción (pg_dump --schema-only)
--   - Columnas nuevas integradas: ubicacion (sm, pa, no_oficial, fecha_ingreso_rpp),
--     localizador_portal (portal), solicitud (cantidad_autorizada, cantidad_facturada),
--     grupo_referencia (cantidad_facturada)
--   - Funciones PL/pgSQL integradas: fn_cancelar_solicitud, fn_editar_cantidad_solicitud
--   - Vistas nuevas integradas: vw_metricas_referencias, vw_ordenes_resumen,
--     vw_referencias_detalle, vw_solicitudes_detalle
--   - Esquema cancunbot_produccion integrado al final
-- ===========================================================================

-- ===========================================================================
-- 1. CREACIÓN DE ESQUEMAS
-- ===========================================================================

CREATE SCHEMA IF NOT EXISTS sar_seguridad;
CREATE SCHEMA IF NOT EXISTS sar_catalogo;
CREATE SCHEMA IF NOT EXISTS sar_produccion;
CREATE SCHEMA IF NOT EXISTS sar_archivo;
CREATE SCHEMA IF NOT EXISTS sar_auditoria;
CREATE SCHEMA IF NOT EXISTS sar_configuracion;
CREATE SCHEMA IF NOT EXISTS sar_reporte;
CREATE SCHEMA IF NOT EXISTS cancunbot_produccion;

COMMENT ON SCHEMA cancunbot_produccion IS 'Esquema del módulo R2F-Cancún. Lotes de folios, folios, recibos y facturas de Tesorería Cancún.';

-- ===========================================================================
-- 2. EXTENSIONES
-- ===========================================================================

-- Habilitar extensión para búsquedas con ILIKE veloces (trigram)
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- ===========================================================================
-- ESQUEMA: sar_seguridad
-- ===========================================================================

-- Tabla: usuario
CREATE TABLE sar_seguridad.usuario (
    usuario_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    nombre VARCHAR(200) NOT NULL,
    correo VARCHAR(200),
    password_hash VARCHAR(500) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ
);

-- Tabla: rol
CREATE TABLE sar_seguridad.rol (
    rol_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(30) NOT NULL UNIQUE,
    nombre VARCHAR(100) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE
);

-- Tabla: usuario_rol
CREATE TABLE sar_seguridad.usuario_rol (
    usuario_id BIGINT NOT NULL,
    rol_id BIGINT NOT NULL,
    PRIMARY KEY (usuario_id, rol_id),
    FOREIGN KEY (usuario_id) REFERENCES sar_seguridad.usuario(usuario_id) ON DELETE CASCADE,
    FOREIGN KEY (rol_id) REFERENCES sar_seguridad.rol(rol_id) ON DELETE CASCADE
);

-- Tabla: app_modulo
CREATE TABLE sar_seguridad.app_modulo (
    app_modulo_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(50) NOT NULL UNIQUE,
    nombre VARCHAR(100) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE
);

-- Tabla: rol_app_modulo
CREATE TABLE sar_seguridad.rol_app_modulo (
    rol_id BIGINT NOT NULL,
    app_modulo_id INTEGER NOT NULL,
    PRIMARY KEY (rol_id, app_modulo_id),
    FOREIGN KEY (rol_id) REFERENCES sar_seguridad.rol(rol_id) ON DELETE CASCADE,
    FOREIGN KEY (app_modulo_id) REFERENCES sar_seguridad.app_modulo(app_modulo_id) ON DELETE CASCADE
);

-- Tabla: modulo
CREATE TABLE sar_seguridad.modulo (
    modulo_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(50) NOT NULL UNIQUE,
    nombre VARCHAR(100) NOT NULL,
    descripcion VARCHAR(200),
    activo BOOLEAN NOT NULL DEFAULT TRUE
);

-- Tabla: accion
CREATE TABLE sar_seguridad.accion (
    accion_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(50) NOT NULL UNIQUE,
    nombre VARCHAR(100) NOT NULL,
    descripcion VARCHAR(200),
    activo BOOLEAN NOT NULL DEFAULT TRUE
);

-- Tabla: permiso
CREATE TABLE sar_seguridad.permiso (
    permiso_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    modulo_id BIGINT NOT NULL,
    accion_id BIGINT NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    FOREIGN KEY (modulo_id) REFERENCES sar_seguridad.modulo(modulo_id) ON DELETE CASCADE,
    FOREIGN KEY (accion_id) REFERENCES sar_seguridad.accion(accion_id) ON DELETE CASCADE,
    CONSTRAINT uq_modulo_accion UNIQUE (modulo_id, accion_id)
);

-- Tabla: rol_permiso
CREATE TABLE sar_seguridad.rol_permiso (
    rol_id BIGINT NOT NULL,
    permiso_id BIGINT NOT NULL,
    PRIMARY KEY (rol_id, permiso_id),
    FOREIGN KEY (rol_id) REFERENCES sar_seguridad.rol(rol_id) ON DELETE CASCADE,
    FOREIGN KEY (permiso_id) REFERENCES sar_seguridad.permiso(permiso_id) ON DELETE CASCADE
);

-- Tabla: sesion
CREATE TABLE sar_seguridad.sesion (
    sesion_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    equipo_nombre VARCHAR(200),
    equipo_uuid VARCHAR(200),
    ip_equipo VARCHAR(100),
    version_cliente VARCHAR(50),
    fecha_inicio TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ultimo_heartbeat TIMESTAMPTZ,
    estado VARCHAR(30),
    FOREIGN KEY (usuario_id) REFERENCES sar_seguridad.usuario(usuario_id) ON DELETE CASCADE
);

-- ===========================================================================
-- ESQUEMA: sar_catalogo
-- ===========================================================================

-- Tabla: municipio
CREATE TABLE sar_catalogo.municipio (
    municipio_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_portal VARCHAR(50),
    nombre VARCHAR(200) NOT NULL,
    activo BOOLEAN DEFAULT TRUE
);

-- Tabla: delegacion
CREATE TABLE sar_catalogo.delegacion (
    delegacion_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    municipio_id BIGINT NOT NULL,
    codigo_portal VARCHAR(300),
    nombre VARCHAR(200) NOT NULL,
    activo BOOLEAN DEFAULT TRUE,
    FOREIGN KEY (municipio_id) REFERENCES sar_catalogo.municipio(municipio_id) ON DELETE RESTRICT
);

-- Tabla: concepto
CREATE TABLE sar_catalogo.concepto (
    concepto_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_portal VARCHAR(300),
    nombre VARCHAR(300) NOT NULL,
    alias VARCHAR(20),
    activo BOOLEAN DEFAULT TRUE
);

-- Tabla: rfc
CREATE TABLE sar_catalogo.rfc (
    rfc_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rfc VARCHAR(13) NOT NULL UNIQUE,
    razon_social VARCHAR(500) NOT NULL,
    calle VARCHAR(500),
    no_exterior VARCHAR(50),
    no_interior VARCHAR(50),
    colonia VARCHAR(300),
    codigo_postal VARCHAR(10),
    localidad VARCHAR(300),
    municipio VARCHAR(300),
    estado VARCHAR(300),
    activo BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ,
    CONSTRAINT chk_rfc_pattern CHECK (rfc ~* '^[A-Z&Ññ]{3,4}[0-9]{6}[A-Z0-9]{3}$')
);

-- Tabla: estado_sistema
CREATE TABLE sar_catalogo.estado_sistema (
    estado_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entidad VARCHAR(100) NOT NULL,
    codigo VARCHAR(50) NOT NULL,
    descripcion VARCHAR(200),
    UNIQUE(entidad, codigo)
);

-- Tabla: notaria
CREATE TABLE sar_catalogo.notaria (
    notaria_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(200) NOT NULL UNIQUE,
    alias VARCHAR(50),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Tabla: colaborador
CREATE TABLE sar_catalogo.colaborador (
    colaborador_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(200) NOT NULL UNIQUE,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Tabla: desarrollo
CREATE TABLE sar_catalogo.desarrollo (
    desarrollo_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(200) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_desarrollo_nombre UNIQUE (nombre)
);

-- Tabla intermedia: desarrollo_empresa
CREATE TABLE sar_catalogo.desarrollo_empresa (
    desarrollo_empresa_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    desarrollo_id BIGINT NOT NULL,
    rfc_id BIGINT NOT NULL,
    delegacion_id BIGINT NOT NULL,
    es_default BOOLEAN NOT NULL DEFAULT FALSE,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (desarrollo_id) REFERENCES sar_catalogo.desarrollo(desarrollo_id) ON DELETE RESTRICT,
    FOREIGN KEY (rfc_id) REFERENCES sar_catalogo.rfc(rfc_id) ON DELETE RESTRICT,
    FOREIGN KEY (delegacion_id) REFERENCES sar_catalogo.delegacion(delegacion_id) ON DELETE RESTRICT,
    CONSTRAINT uq_desarrollo_empresa_delegacion UNIQUE (desarrollo_id, rfc_id, delegacion_id)
);

-- Tabla: evento_sistema
CREATE TABLE sar_catalogo.evento_sistema (
    evento_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(100) NOT NULL UNIQUE,
    descripcion VARCHAR(300)
);

-- ===========================================================================
-- ESQUEMA: sar_produccion
-- ===========================================================================

-- Tabla: orden_generacion
CREATE TABLE sar_produccion.orden_generacion (
    orden_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    folio VARCHAR(50) NOT NULL UNIQUE,
    descripcion TEXT,
    municipio_id BIGINT NOT NULL DEFAULT 2,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    estado_id BIGINT NOT NULL,
    usuario_id BIGINT NOT NULL,
    FOREIGN KEY (municipio_id) REFERENCES sar_catalogo.municipio(municipio_id) ON DELETE RESTRICT,
    FOREIGN KEY (estado_id) REFERENCES sar_catalogo.estado_sistema(estado_id) ON DELETE RESTRICT,
    FOREIGN KEY (usuario_id) REFERENCES sar_seguridad.usuario(usuario_id) ON DELETE RESTRICT
);

-- Tabla: grupo_referencia
CREATE TABLE sar_produccion.grupo_referencia (
    grupo_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    orden_id BIGINT NOT NULL,
    rfc_id BIGINT NOT NULL,
    concepto_id BIGINT NOT NULL,
    cantidad_solicitada INTEGER NOT NULL,
    cantidad_generada INTEGER DEFAULT 0,
    cantidad_autorizada INTEGER DEFAULT 0,
    cantidad_rechazada INTEGER DEFAULT 0,
    cantidad_expirada INTEGER DEFAULT 0,
    cantidad_facturada INTEGER DEFAULT 0,
    ultimo_consecutivo INTEGER DEFAULT 0,
    estado_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (orden_id) REFERENCES sar_produccion.orden_generacion(orden_id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (rfc_id) REFERENCES sar_catalogo.rfc(rfc_id) ON DELETE RESTRICT,
    FOREIGN KEY (concepto_id) REFERENCES sar_catalogo.concepto(concepto_id) ON DELETE RESTRICT,
    FOREIGN KEY (estado_id) REFERENCES sar_catalogo.estado_sistema(estado_id) ON DELETE RESTRICT,
    CONSTRAINT uq_grupo UNIQUE (orden_id, rfc_id, concepto_id)
);

-- Tabla: solicitud
CREATE TABLE sar_produccion.solicitud (
    solicitud_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grupo_id BIGINT NOT NULL,
    delegacion_id BIGINT NOT NULL,
    cantidad_solicitada INTEGER NOT NULL,
    cantidad_generada INTEGER DEFAULT 0,
    cantidad_autorizada INTEGER DEFAULT 0,
    cantidad_facturada INTEGER DEFAULT 0,
    consecutivo_inicio INTEGER NOT NULL,
    consecutivo_fin INTEGER NOT NULL,
    ultimo_consecutivo INTEGER DEFAULT 0,
    usuario_asignado BIGINT,
    estado_id BIGINT NOT NULL,
    fecha_asignacion TIMESTAMPTZ,
    fecha_inicio TIMESTAMPTZ,
    fecha_fin TIMESTAMPTZ,
    FOREIGN KEY (grupo_id) REFERENCES sar_produccion.grupo_referencia(grupo_id) ON DELETE CASCADE,
    FOREIGN KEY (delegacion_id) REFERENCES sar_catalogo.delegacion(delegacion_id) ON DELETE RESTRICT,
    FOREIGN KEY (usuario_asignado) REFERENCES sar_seguridad.usuario(usuario_id) ON DELETE SET NULL,
    FOREIGN KEY (estado_id) REFERENCES sar_catalogo.estado_sistema(estado_id) ON DELETE RESTRICT
);

-- Tabla: referencia
CREATE TABLE sar_produccion.referencia (
    referencia_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grupo_id BIGINT NOT NULL,
    solicitud_id BIGINT NOT NULL,
    consecutivo_grupo INTEGER NOT NULL,
    referencia_portal VARCHAR(100) NOT NULL UNIQUE,
    importe NUMERIC(14,2),
    fecha_generacion TIMESTAMPTZ NOT NULL,
    fecha_vigencia DATE,
    usuario_asignado BIGINT,
    estado_id BIGINT NOT NULL,
    cantidad INTEGER NOT NULL DEFAULT 1,
    porcentaje INTEGER NOT NULL DEFAULT 100,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (grupo_id) REFERENCES sar_produccion.grupo_referencia(grupo_id) ON DELETE CASCADE,
    FOREIGN KEY (solicitud_id) REFERENCES sar_produccion.solicitud(solicitud_id) ON DELETE CASCADE,
    FOREIGN KEY (usuario_asignado) REFERENCES sar_seguridad.usuario(usuario_id) ON DELETE SET NULL,
    FOREIGN KEY (estado_id) REFERENCES sar_catalogo.estado_sistema(estado_id) ON DELETE RESTRICT,
    CONSTRAINT uq_referencia_grupo UNIQUE (grupo_id, consecutivo_grupo)
);

-- ===========================================================================
-- ESQUEMA: sar_archivo
-- ===========================================================================

-- Tabla: archivo_pdf
CREATE TABLE sar_archivo.archivo_pdf (
    archivo_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    referencia_id BIGINT NOT NULL,
    tipo_archivo VARCHAR(50) NOT NULL,
    estado_archivo VARCHAR(30) NOT NULL,
    nombre_archivo VARCHAR(500) NOT NULL,
    ruta_archivo VARCHAR(1000) NOT NULL,
    hash_sha256 VARCHAR(64) NOT NULL,
    tamano_bytes BIGINT NOT NULL,
    fecha_creacion TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (referencia_id) REFERENCES sar_produccion.referencia(referencia_id) ON DELETE CASCADE
);

-- Tabla: factura
CREATE TABLE sar_archivo.factura (
    factura_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    referencia_id BIGINT NOT NULL,
    uuid VARCHAR(36) NOT NULL UNIQUE,
    nombre_archivo VARCHAR(100),
    rfc_emisor VARCHAR(13) NOT NULL,
    fecha_factura TIMESTAMPTZ NOT NULL,
    pdf_path VARCHAR(1000),
    pdf2_path VARCHAR(1000),
    estado VARCHAR(30) NOT NULL,
    delegacion VARCHAR(100),
    FOREIGN KEY (referencia_id) REFERENCES sar_produccion.referencia(referencia_id) ON DELETE RESTRICT
);

-- Tabla: lote_asignacion
CREATE TABLE sar_archivo.lote_asignacion (
    lote_asignacion_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_destino VARCHAR(20) NOT NULL, -- 'NOTARIA' o 'COLABORADOR'
    notaria_id BIGINT,
    colaborador_id BIGINT,
    solicitante_externo VARCHAR(200),
    fecha TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    observaciones TEXT,
    usuario_creacion BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (notaria_id) REFERENCES sar_catalogo.notaria(notaria_id) ON DELETE RESTRICT,
    FOREIGN KEY (colaborador_id) REFERENCES sar_catalogo.colaborador(colaborador_id) ON DELETE RESTRICT,
    FOREIGN KEY (usuario_creacion) REFERENCES sar_seguridad.usuario(usuario_id) ON DELETE RESTRICT,
    CONSTRAINT chk_lote_asignacion_tipo_destino CHECK (tipo_destino IN ('NOTARIA', 'COLABORADOR')),
    CONSTRAINT chk_lote_asignacion_destino CHECK (
        (tipo_destino = 'NOTARIA' AND notaria_id IS NOT NULL AND colaborador_id IS NULL)
        OR
        (tipo_destino = 'COLABORADOR' AND colaborador_id IS NOT NULL AND notaria_id IS NULL)
    )
);

-- Tabla: ubicacion
CREATE TABLE sar_archivo.ubicacion (
    ubicacion_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    desarrollo_id BIGINT NOT NULL,
    sm VARCHAR(50),
    mz VARCHAR(50),
    lote VARCHAR(50),
    edif VARCHAR(50),
    viv VARCHAR(50),
    lote_id_erp VARCHAR(100),
    descripcion TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (desarrollo_id) REFERENCES sar_catalogo.desarrollo(desarrollo_id) ON DELETE RESTRICT
);

-- Tabla: lote_detalle
CREATE TABLE sar_archivo.lote_detalle (
    lote_detalle_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lote_asignacion_id BIGINT NOT NULL,
    rfc_id BIGINT NOT NULL,
    concepto_id BIGINT NOT NULL,
    desarrollo_id BIGINT,
    cantidad_solicitada INTEGER NOT NULL,
    cantidad_confirmada INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (lote_asignacion_id) REFERENCES sar_archivo.lote_asignacion(lote_asignacion_id) ON DELETE CASCADE,
    FOREIGN KEY (rfc_id) REFERENCES sar_catalogo.rfc(rfc_id) ON DELETE RESTRICT,
    FOREIGN KEY (concepto_id) REFERENCES sar_catalogo.concepto(concepto_id) ON DELETE RESTRICT,
    FOREIGN KEY (desarrollo_id) REFERENCES sar_catalogo.desarrollo(desarrollo_id) ON DELETE RESTRICT
);

-- Tabla: asignacion_referencia
CREATE TABLE sar_archivo.asignacion_referencia (
    asignacion_referencia_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lote_detalle_id BIGINT NOT NULL,
    referencia_id BIGINT NOT NULL,
    ubicacion_id BIGINT,
    intento INTEGER NOT NULL DEFAULT 1,
    estado_id BIGINT NOT NULL,
    cliente VARCHAR(250),
    credito_titular VARCHAR(250),
    pa VARCHAR(250),
    no_oficial VARCHAR(250),
    fecha_solicitud DATE,
    fecha_reporte_notaria DATE,
    fecha_ingreso_rpp DATE,
    fecha_escritura DATE,
    fecha_titulacion DATE,
    comentarios TEXT,
    fecha_asignacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    usuario_asignacion BIGINT NOT NULL,
    fecha_confirmacion TIMESTAMPTZ,
    usuario_confirmacion BIGINT,
    observaciones TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (lote_detalle_id) REFERENCES sar_archivo.lote_detalle(lote_detalle_id) ON DELETE CASCADE,
    FOREIGN KEY (referencia_id) REFERENCES sar_produccion.referencia(referencia_id) ON DELETE RESTRICT,
    FOREIGN KEY (ubicacion_id) REFERENCES sar_archivo.ubicacion(ubicacion_id) ON DELETE RESTRICT,
    FOREIGN KEY (estado_id) REFERENCES sar_catalogo.estado_sistema(estado_id) ON DELETE RESTRICT,
    FOREIGN KEY (usuario_asignacion) REFERENCES sar_seguridad.usuario(usuario_id) ON DELETE RESTRICT,
    FOREIGN KEY (usuario_confirmacion) REFERENCES sar_seguridad.usuario(usuario_id) ON DELETE RESTRICT,
    CONSTRAINT chk_asignacion_referencia_intento CHECK (intento >= 1),
    CONSTRAINT chk_asignacion_referencia_confirmacion CHECK (
        (fecha_confirmacion IS NULL AND usuario_confirmacion IS NULL)
        OR
        (fecha_confirmacion IS NOT NULL AND usuario_confirmacion IS NOT NULL)
    ),
    CONSTRAINT uq_asignacion_referencia_referencia UNIQUE (referencia_id),
    CONSTRAINT uq_ubicacion_lote_detalle_intento UNIQUE (ubicacion_id, lote_detalle_id, intento)
);

-- ===========================================================================
-- ESQUEMA: sar_auditoria
-- ===========================================================================

-- Tabla: auditoria_login
CREATE TABLE sar_auditoria.auditoria_login (
    login_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT,
    sesion_id BIGINT,
    fecha_login TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_logout TIMESTAMPTZ,
    ip VARCHAR(100),
    equipo VARCHAR(200),
    FOREIGN KEY (usuario_id) REFERENCES sar_seguridad.usuario(usuario_id) ON DELETE SET NULL,
    FOREIGN KEY (sesion_id) REFERENCES sar_seguridad.sesion(sesion_id) ON DELETE SET NULL
);

-- Tabla: auditoria_evento
CREATE TABLE sar_auditoria.auditoria_evento (
    evento_auditoria_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evento_id BIGINT NOT NULL,
    usuario_id BIGINT,
    sesion_id BIGINT,
    fecha TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    modulo VARCHAR(100) NOT NULL,
    valor_anterior JSONB,
    valor_nuevo JSONB,
    detalle JSONB,
    FOREIGN KEY (evento_id) REFERENCES sar_catalogo.evento_sistema(evento_id) ON DELETE RESTRICT,
    FOREIGN KEY (usuario_id) REFERENCES sar_seguridad.usuario(usuario_id) ON DELETE SET NULL,
    FOREIGN KEY (sesion_id) REFERENCES sar_seguridad.sesion(sesion_id) ON DELETE SET NULL
);

-- Tabla: auditoria_error
CREATE TABLE sar_auditoria.auditoria_error (
    error_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT,
    sesion_id BIGINT,
    modulo VARCHAR(100) NOT NULL,
    mensaje TEXT NOT NULL,
    stack_trace TEXT,
    fecha TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (usuario_id) REFERENCES sar_seguridad.usuario(usuario_id) ON DELETE SET NULL,
    FOREIGN KEY (sesion_id) REFERENCES sar_seguridad.sesion(sesion_id) ON DELETE SET NULL
);

-- ===========================================================================
-- ESQUEMA: sar_configuracion
-- ===========================================================================

-- Tabla: parametro_sistema
CREATE TABLE sar_configuracion.parametro_sistema (
    parametro_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(100) NOT NULL UNIQUE,
    valor TEXT NOT NULL,
    descripcion TEXT,
    activo BOOLEAN NOT NULL DEFAULT TRUE
);

-- Tabla: localizador_portal
-- Columna 'portal': SAR = Tributanet/SATQ | CANCUN_RECIBO / CANCUN_FACTURA = R2F-Cancún
CREATE TABLE sar_configuracion.localizador_portal (
    localizador_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_clave VARCHAR(100) NOT NULL UNIQUE,
    label_visible VARCHAR(200) NOT NULL,
    estrategia_selector VARCHAR(50) NOT NULL,
    valor_selector VARCHAR(500) NOT NULL,
    descripcion VARCHAR(500),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    portal VARCHAR(50) DEFAULT 'SAR'
);

-- ===========================================================================
-- ESQUEMA: cancunbot_produccion
-- ===========================================================================

-- Tabla: lote_folio
-- Lote de folios a procesar. Origen: Excel importado o captura manual.
CREATE TABLE cancunbot_produccion.lote_folio (
    lote_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    folio_lote VARCHAR(50) NOT NULL,   -- Folio único del lote (ej: LOT-2026-001)
    descripcion TEXT,
    origen VARCHAR(20) NOT NULL DEFAULT 'EXCEL', -- EXCEL o MANUAL
    total_folios INTEGER NOT NULL DEFAULT 0,
    folios_procesados INTEGER NOT NULL DEFAULT 0,
    folios_error INTEGER NOT NULL DEFAULT 0,
    folios_facturados INTEGER NOT NULL DEFAULT 0,
    archivo_excel VARCHAR(500),
    estado_id BIGINT NOT NULL,
    usuario_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ,
    FOREIGN KEY (estado_id) REFERENCES sar_catalogo.estado_sistema(estado_id) ON DELETE RESTRICT,
    FOREIGN KEY (usuario_id) REFERENCES sar_seguridad.usuario(usuario_id) ON DELETE RESTRICT,
    CONSTRAINT chk_lote_origen CHECK (origen IN ('EXCEL', 'MANUAL'))
);

-- Tabla: folio_cancun
-- Folio individual a procesar. Unidad de trabajo de Bot Recibos y Bot Facturas.
CREATE TABLE cancunbot_produccion.folio_cancun (
    folio_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lote_id BIGINT NOT NULL,
    folio_electronico VARCHAR(100),    -- Folio electrónico (ej: F-2026-615-31044)
    folio_pase_caja VARCHAR(100),
    tipo_folio VARCHAR(20) NOT NULL DEFAULT 'ELECTRONICO',
    intentos INTEGER NOT NULL DEFAULT 0, -- Número de intentos de descarga realizados
    ultimo_error TEXT,
    estado_id BIGINT NOT NULL,
    rfc_id INTEGER,           -- Referencia opcional al RFC en el catálogo de SAR
    desarrollo_id INTEGER,    -- Referencia opcional al desarrollo en el catálogo de SAR
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ,
    FOREIGN KEY (lote_id) REFERENCES cancunbot_produccion.lote_folio(lote_id) ON DELETE CASCADE,
    FOREIGN KEY (estado_id) REFERENCES sar_catalogo.estado_sistema(estado_id) ON DELETE RESTRICT,
    FOREIGN KEY (rfc_id) REFERENCES sar_catalogo.rfc(rfc_id) ON DELETE SET NULL,
    FOREIGN KEY (desarrollo_id) REFERENCES sar_catalogo.desarrollo(desarrollo_id) ON DELETE SET NULL,
    CONSTRAINT chk_folio_tipo CHECK (tipo_folio IN ('ELECTRONICO', 'PASE_CAJA')),
    CONSTRAINT chk_folio_no_nulo CHECK (folio_electronico IS NOT NULL OR folio_pase_caja IS NOT NULL)
);

-- Tabla: recibo_cancun
-- Datos extraídos del PDF de recibo electrónico. 1-a-1 con folio_cancun.
CREATE TABLE cancunbot_produccion.recibo_cancun (
    recibo_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    folio_id BIGINT NOT NULL,
    folio_pase_caja VARCHAR(100),
    folio_electronico VARCHAR(100),
    fecha_expedicion DATE,
    hora_expedicion TIME,
    lugar_expedicion VARCHAR(300),
    rfc VARCHAR(13),
    contribucion VARCHAR(300),
    nombre_contribuyente VARCHAR(500),
    concepto TEXT,
    total NUMERIC(14,2),
    forma_pago VARCHAR(100),
    detalle_concepto JSONB,       -- JSONB para campos extras del PDF sin modificar el esquema
    pdf_nombre VARCHAR(500),
    pdf_ruta VARCHAR(1000),
    hash_sha256 VARCHAR(64),      -- SHA256 del PDF descargado para verificación de integridad
    correo_factura VARCHAR(200),  -- Correo del contribuyente para recibir la factura CFDI
    estado_id BIGINT NOT NULL,
    padron VARCHAR(100),          -- Padrón del contribuyente extraído del detalle de cobro
    clave_catastral VARCHAR(100), -- Clave Catastral del predio extraída del detalle de cobro
    rfc_id INTEGER,               -- Referencia oficial verificada al RFC en el catálogo de SAR
    sm VARCHAR(50),               -- Super manzana catastral extraída de concepto/domicilio
    mz VARCHAR(50),               -- Manzana catastral extraída de concepto/domicilio
    l VARCHAR(50),                -- Lote catastral extraído de concepto/domicilio
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ,
    FOREIGN KEY (folio_id) REFERENCES cancunbot_produccion.folio_cancun(folio_id) ON DELETE CASCADE,
    FOREIGN KEY (estado_id) REFERENCES sar_catalogo.estado_sistema(estado_id) ON DELETE RESTRICT,
    FOREIGN KEY (rfc_id) REFERENCES sar_catalogo.rfc(rfc_id) ON DELETE SET NULL
);

-- Tabla: factura_cancun
-- Factura CFDI generada. 1-a-1 con recibo_cancun.
CREATE TABLE cancunbot_produccion.factura_cancun (
    factura_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recibo_id BIGINT NOT NULL,
    uuid_cfdi VARCHAR(36),            -- UUID fiscal único del CFDI
    folio_fiscal VARCHAR(100),
    rfc_emisor VARCHAR(13),
    rfc_receptor VARCHAR(13),
    razon_social_receptor VARCHAR(500),
    cp_receptor VARCHAR(10),
    fecha_timbrado TIMESTAMPTZ,
    pdf_path VARCHAR(1000),
    xml_path VARCHAR(1000),
    datos_adicionales JSONB,          -- JSONB para datos extras del portal de facturación
    estado VARCHAR(30) NOT NULL DEFAULT 'PENDIENTE',
    mensaje_error TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ,
    FOREIGN KEY (recibo_id) REFERENCES cancunbot_produccion.recibo_cancun(recibo_id) ON DELETE RESTRICT
);

-- ===========================================================================
-- ÍNDICES DE RENDIMIENTO (PERFORMANCE INDEXES)
-- ===========================================================================

-- 1. Esquema: sar_seguridad
CREATE INDEX IF NOT EXISTS idx_usuario_rol_rol_id    ON sar_seguridad.usuario_rol (rol_id);
CREATE INDEX IF NOT EXISTS idx_sesion_usuario_id      ON sar_seguridad.sesion (usuario_id);
CREATE INDEX IF NOT EXISTS idx_sesion_estado          ON sar_seguridad.sesion (estado);                          -- Filtrar sesiones activas/inactivas
CREATE INDEX IF NOT EXISTS idx_rol_permiso_permiso_id ON sar_seguridad.rol_permiso (permiso_id);
CREATE INDEX IF NOT EXISTS idx_permiso_modulo_id      ON sar_seguridad.permiso (modulo_id);
CREATE INDEX IF NOT EXISTS idx_permiso_accion_id      ON sar_seguridad.permiso (accion_id);

-- 2. Esquema: sar_catalogo
CREATE INDEX IF NOT EXISTS idx_delegacion_municipio_id         ON sar_catalogo.delegacion (municipio_id);              -- FK join catalogos
CREATE INDEX IF NOT EXISTS idx_desarrollo_empresa_desarrollo_id ON sar_catalogo.desarrollo_empresa (desarrollo_id);   -- FK join frecuente
CREATE INDEX IF NOT EXISTS idx_desarrollo_empresa_rfc_id        ON sar_catalogo.desarrollo_empresa (rfc_id);           -- FK join frecuente

-- 3. Esquema: sar_produccion
CREATE INDEX IF NOT EXISTS idx_grupo_referencia_orden_id      ON sar_produccion.grupo_referencia (orden_id);
CREATE INDEX IF NOT EXISTS idx_grupo_referencia_estado_id     ON sar_produccion.grupo_referencia (estado_id);
CREATE INDEX IF NOT EXISTS idx_solicitud_grupo_id             ON sar_produccion.solicitud (grupo_id);
CREATE INDEX IF NOT EXISTS idx_solicitud_estado_id            ON sar_produccion.solicitud (estado_id);
CREATE INDEX IF NOT EXISTS idx_solicitud_usuario_asignado     ON sar_produccion.solicitud (usuario_asignado);
CREATE INDEX IF NOT EXISTS idx_solicitud_grupo_estado         ON sar_produccion.solicitud (grupo_id, estado_id);       -- Compuesto: filtro común grupo+estado
CREATE INDEX IF NOT EXISTS idx_referencia_grupo_id            ON sar_produccion.referencia (grupo_id);
CREATE INDEX IF NOT EXISTS idx_referencia_solicitud_id        ON sar_produccion.referencia (solicitud_id);
CREATE INDEX IF NOT EXISTS idx_referencia_estado_id           ON sar_produccion.referencia (estado_id);
CREATE INDEX IF NOT EXISTS idx_referencia_fecha_vigencia      ON sar_produccion.referencia (fecha_vigencia);
CREATE INDEX IF NOT EXISTS idx_referencia_grupo_estado        ON sar_produccion.referencia (grupo_id, estado_id);      -- Compuesto: filtro común grupo+estado
CREATE INDEX IF NOT EXISTS idx_referencia_portal_trgm         ON sar_produccion.referencia USING gin (referencia_portal gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_orden_folio_trgm               ON sar_produccion.orden_generacion USING gin (folio gin_trgm_ops);

-- 4. Esquema: sar_archivo
CREATE INDEX IF NOT EXISTS idx_archivo_pdf_referencia_id          ON sar_archivo.archivo_pdf (referencia_id);
CREATE INDEX IF NOT EXISTS idx_factura_referencia_id              ON sar_archivo.factura (referencia_id);
CREATE INDEX IF NOT EXISTS idx_factura_rfc_emisor                 ON sar_archivo.factura (rfc_emisor);
CREATE INDEX IF NOT EXISTS idx_factura_fecha_factura              ON sar_archivo.factura (fecha_factura DESC);
CREATE INDEX IF NOT EXISTS idx_lote_asignacion_destino            ON sar_archivo.lote_asignacion (tipo_destino);
CREATE INDEX IF NOT EXISTS idx_lote_asignacion_notaria            ON sar_archivo.lote_asignacion (notaria_id);
CREATE INDEX IF NOT EXISTS idx_lote_asignacion_colaborador        ON sar_archivo.lote_asignacion (colaborador_id);
CREATE INDEX IF NOT EXISTS idx_lote_asignacion_fecha              ON sar_archivo.lote_asignacion (fecha);
CREATE INDEX IF NOT EXISTS idx_lote_asignacion_usuario            ON sar_archivo.lote_asignacion (usuario_creacion);
CREATE INDEX IF NOT EXISTS idx_ubicacion_desarrollo               ON sar_archivo.ubicacion (desarrollo_id);
CREATE INDEX IF NOT EXISTS idx_lote_detalle_lote                  ON sar_archivo.lote_detalle (lote_asignacion_id);
CREATE INDEX IF NOT EXISTS idx_lote_detalle_rfc                   ON sar_archivo.lote_detalle (rfc_id);                 -- FK: búsqueda por empresa
CREATE INDEX IF NOT EXISTS idx_lote_detalle_desarrollo            ON sar_archivo.lote_detalle (desarrollo_id);          -- FK: búsqueda por desarrollo
CREATE INDEX IF NOT EXISTS idx_asignacion_referencia_detalle      ON sar_archivo.asignacion_referencia (lote_detalle_id);
CREATE INDEX IF NOT EXISTS idx_asignacion_referencia_ubicacion    ON sar_archivo.asignacion_referencia (ubicacion_id);
CREATE INDEX IF NOT EXISTS idx_asignacion_referencia_referencia   ON sar_archivo.asignacion_referencia (referencia_id);
CREATE INDEX IF NOT EXISTS idx_asignacion_referencia_estado       ON sar_archivo.asignacion_referencia (estado_id);
CREATE INDEX IF NOT EXISTS idx_asignacion_referencia_usuario      ON sar_archivo.asignacion_referencia (usuario_asignacion);
CREATE INDEX IF NOT EXISTS idx_asignacion_ubicacion_fecha         ON sar_archivo.asignacion_referencia (ubicacion_id, fecha_asignacion DESC);
CREATE INDEX IF NOT EXISTS idx_asignacion_pendiente_confirmacion  ON sar_archivo.asignacion_referencia (lote_detalle_id) WHERE fecha_confirmacion IS NULL; -- Parcial: asignaciones sin confirmar

-- 5. Esquema: sar_auditoria
CREATE INDEX IF NOT EXISTS idx_auditoria_login_usuario_id  ON sar_auditoria.auditoria_login (usuario_id);
CREATE INDEX IF NOT EXISTS idx_auditoria_login_sesion_id   ON sar_auditoria.auditoria_login (sesion_id);
CREATE INDEX IF NOT EXISTS idx_auditoria_evento_evento_id  ON sar_auditoria.auditoria_evento (evento_id);
CREATE INDEX IF NOT EXISTS idx_auditoria_evento_usuario_id ON sar_auditoria.auditoria_evento (usuario_id);
CREATE INDEX IF NOT EXISTS idx_auditoria_evento_fecha      ON sar_auditoria.auditoria_evento (fecha DESC);
CREATE INDEX IF NOT EXISTS idx_auditoria_error_fecha       ON sar_auditoria.auditoria_error (fecha DESC);

-- 6. Esquema: cancunbot_produccion
CREATE INDEX IF NOT EXISTS idx_lote_folio_estado_id        ON cancunbot_produccion.lote_folio (estado_id);       -- Filtrar lotes por estado
CREATE INDEX IF NOT EXISTS idx_lote_folio_usuario_id       ON cancunbot_produccion.lote_folio (usuario_id);      -- Filtrar lotes por usuario
CREATE INDEX IF NOT EXISTS idx_folio_cancun_lote_id        ON cancunbot_produccion.folio_cancun (lote_id);
CREATE INDEX IF NOT EXISTS idx_folio_cancun_estado_id      ON cancunbot_produccion.folio_cancun (estado_id);
CREATE INDEX IF NOT EXISTS idx_recibo_cancun_folio_id      ON cancunbot_produccion.recibo_cancun (folio_id);
CREATE INDEX IF NOT EXISTS idx_recibo_cancun_estado_id     ON cancunbot_produccion.recibo_cancun (estado_id);
CREATE INDEX IF NOT EXISTS idx_recibo_cancun_rfc           ON cancunbot_produccion.recibo_cancun (rfc);
CREATE INDEX IF NOT EXISTS idx_factura_cancun_recibo       ON cancunbot_produccion.factura_cancun (recibo_id);
CREATE INDEX IF NOT EXISTS idx_factura_cancun_estado       ON cancunbot_produccion.factura_cancun (estado);

-- ===========================================================================
-- VISTAS: sar_produccion
-- ===========================================================================

-- Vista: vw_solicitudes_detalle
CREATE OR REPLACE VIEW sar_produccion.vw_solicitudes_detalle AS
SELECT
    s.solicitud_id,
    s.grupo_id,
    og.folio,
    rfc.razon_social AS rfc_razon_social,
    c.nombre AS concepto_nombre,
    d.nombre AS delegacion_nombre,
    s.cantidad_solicitada,
    s.cantidad_generada,
    es.codigo AS estado_codigo,
    u.nombre AS usuario_asignado_nombre,
    s.fecha_inicio
FROM sar_produccion.solicitud s
JOIN sar_produccion.grupo_referencia gr ON s.grupo_id = gr.grupo_id
JOIN sar_produccion.orden_generacion og ON gr.orden_id = og.orden_id
JOIN sar_catalogo.rfc rfc ON gr.rfc_id = rfc.rfc_id
JOIN sar_catalogo.concepto c ON gr.concepto_id = c.concepto_id
LEFT JOIN sar_catalogo.delegacion d ON s.delegacion_id = d.delegacion_id
JOIN sar_catalogo.estado_sistema es ON s.estado_id = es.estado_id
LEFT JOIN sar_seguridad.usuario u ON s.usuario_asignado = u.usuario_id;

-- Vista: vw_referencias_detalle
CREATE OR REPLACE VIEW sar_produccion.vw_referencias_detalle AS
SELECT
    r.referencia_id,
    r.referencia_portal,
    r.consecutivo_grupo,
    r.importe,
    r.fecha_generacion,
    r.fecha_vigencia,
    og.folio AS folio_orden,
    r.grupo_id,
    rfc.razon_social AS rfc_razon_social,
    c.nombre AS concepto_nombre,
    d.nombre AS delegacion_nombre,
    es.codigo AS estado_codigo,
    u.nombre AS usuario_asignado_nombre
FROM sar_produccion.referencia r
JOIN sar_produccion.grupo_referencia gr ON r.grupo_id = gr.grupo_id
JOIN sar_produccion.orden_generacion og ON gr.orden_id = og.orden_id
JOIN sar_catalogo.rfc rfc ON gr.rfc_id = rfc.rfc_id
JOIN sar_catalogo.concepto c ON gr.concepto_id = c.concepto_id
JOIN sar_produccion.solicitud s ON r.solicitud_id = s.solicitud_id
LEFT JOIN sar_catalogo.delegacion d ON s.delegacion_id = d.delegacion_id
JOIN sar_catalogo.estado_sistema es ON r.estado_id = es.estado_id
LEFT JOIN sar_seguridad.usuario u ON r.usuario_asignado = u.usuario_id;

-- Vista: vw_ordenes_resumen
CREATE OR REPLACE VIEW sar_produccion.vw_ordenes_resumen AS
SELECT
    o.orden_id,
    o.folio,
    o.descripcion,
    o.fecha_creacion,
    u.nombre AS creador,
    COALESCE(SUM(gr.cantidad_solicitada), 0) AS total_solicitadas,
    COALESCE(SUM(gr.cantidad_generada), 0) AS total_generadas
FROM sar_produccion.orden_generacion o
JOIN sar_seguridad.usuario u ON o.usuario_id = u.usuario_id
LEFT JOIN sar_produccion.grupo_referencia gr ON o.orden_id = gr.orden_id
GROUP BY o.orden_id, o.folio, o.descripcion, o.fecha_creacion, u.nombre;

-- Vista: vw_metricas_referencias
CREATE OR REPLACE VIEW sar_produccion.vw_metricas_referencias AS
SELECT
    r.referencia_id,
    r.grupo_id,
    r.solicitud_id,
    r.importe,
    r.fecha_generacion,
    gr.orden_id,
    og.folio AS folio_orden,
    gr.rfc_id,
    rfc.rfc AS rfc_nombre,
    rfc.razon_social AS rfc_razon_social,
    gr.concepto_id,
    c.nombre AS concepto_nombre,
    s.delegacion_id,
    d.nombre AS delegacion_nombre,
    es.codigo AS estado_codigo,
    es.descripcion AS estado_descripcion
FROM sar_produccion.referencia r
JOIN sar_produccion.grupo_referencia gr ON r.grupo_id = gr.grupo_id
JOIN sar_produccion.orden_generacion og ON gr.orden_id = og.orden_id
JOIN sar_produccion.solicitud s ON r.solicitud_id = s.solicitud_id
JOIN sar_catalogo.rfc rfc ON gr.rfc_id = rfc.rfc_id
JOIN sar_catalogo.concepto c ON gr.concepto_id = c.concepto_id
LEFT JOIN sar_catalogo.delegacion d ON s.delegacion_id = d.delegacion_id
JOIN sar_catalogo.estado_sistema es ON r.estado_id = es.estado_id;

-- ===========================================================================
-- FUNCIONES PL/pgSQL: sar_produccion
-- ===========================================================================

-- Función: fn_cancelar_solicitud
-- Cancela una solicitud en estado PENDIENTE y ajusta el contador del grupo.
CREATE OR REPLACE FUNCTION sar_produccion.fn_cancelar_solicitud(
    p_solicitud_id BIGINT
) RETURNS BOOLEAN AS $$
DECLARE
    v_estado_actual_id BIGINT;
    v_codigo_actual VARCHAR;
    v_estado_cancelado_id BIGINT;
    v_grupo_id BIGINT;
    v_cantidad_solicitada INT;
BEGIN
    SELECT estado_id INTO v_estado_cancelado_id FROM sar_catalogo.estado_sistema WHERE codigo = 'CANCELADO' LIMIT 1;
    IF v_estado_cancelado_id IS NULL THEN
        INSERT INTO sar_catalogo.estado_sistema (entidad, codigo, descripcion) VALUES ('GENERAL', 'CANCELADO', 'CANCELADO') RETURNING estado_id INTO v_estado_cancelado_id;
    END IF;

    SELECT estado_id, grupo_id, cantidad_solicitada
    INTO v_estado_actual_id, v_grupo_id, v_cantidad_solicitada
    FROM sar_produccion.solicitud
    WHERE solicitud_id = p_solicitud_id FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Solicitud no encontrada.';
    END IF;

    SELECT codigo INTO v_codigo_actual FROM sar_catalogo.estado_sistema WHERE estado_id = v_estado_actual_id;

    IF v_codigo_actual != 'PENDIENTE' THEN
        RAISE EXCEPTION 'Solo se pueden cancelar solicitudes en estado PENDIENTE. (Estado actual: %)', v_codigo_actual;
    END IF;

    UPDATE sar_produccion.solicitud
    SET estado_id = v_estado_cancelado_id
    WHERE solicitud_id = p_solicitud_id;

    UPDATE sar_produccion.grupo_referencia
    SET cantidad_solicitada = cantidad_solicitada - v_cantidad_solicitada
    WHERE grupo_id = v_grupo_id;

    RETURN TRUE;
END;
$$ LANGUAGE plpgsql;

-- Función: fn_editar_cantidad_solicitud
-- Edita la cantidad de una solicitud en estado PENDIENTE y ajusta el grupo.
CREATE OR REPLACE FUNCTION sar_produccion.fn_editar_cantidad_solicitud(
    p_solicitud_id BIGINT,
    p_nueva_cantidad INT
) RETURNS BOOLEAN AS $$
DECLARE
    v_estado_actual_id BIGINT;
    v_codigo_actual VARCHAR;
    v_grupo_id BIGINT;
    v_cantidad_actual INT;
    v_diferencia INT;
BEGIN
    IF p_nueva_cantidad <= 0 THEN
        RAISE EXCEPTION 'La cantidad debe ser mayor a 0.';
    END IF;

    SELECT estado_id, grupo_id, cantidad_solicitada
    INTO v_estado_actual_id, v_grupo_id, v_cantidad_actual
    FROM sar_produccion.solicitud
    WHERE solicitud_id = p_solicitud_id FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Solicitud no encontrada.';
    END IF;

    SELECT codigo INTO v_codigo_actual FROM sar_catalogo.estado_sistema WHERE estado_id = v_estado_actual_id;

    IF v_codigo_actual != 'PENDIENTE' THEN
        RAISE EXCEPTION 'Solo se pueden editar solicitudes en estado PENDIENTE. (Estado actual: %)', v_codigo_actual;
    END IF;

    v_diferencia := p_nueva_cantidad - v_cantidad_actual;

    UPDATE sar_produccion.solicitud
    SET cantidad_solicitada = p_nueva_cantidad
    WHERE solicitud_id = p_solicitud_id;

    UPDATE sar_produccion.grupo_referencia
    SET cantidad_solicitada = cantidad_solicitada + v_diferencia
    WHERE grupo_id = v_grupo_id;

    RETURN TRUE;
END;
$$ LANGUAGE plpgsql;

-- ===========================================================================
-- DATOS SEMILLA (SEED DATA)
-- ===========================================================================

-- Módulos de Aplicación (acceso por módulo de app)
INSERT INTO sar_seguridad.app_modulo (codigo, nombre, activo) VALUES
('ADMIN',      'Administración',          TRUE),
('CTRL_REF',   'Control de Referencias',  TRUE),
('BOT_FACE_A', 'Bot-Pago de derechos',    TRUE),
('BOT_C',      'Bot-Facturación',         TRUE)
ON CONFLICT (codigo) DO NOTHING;

-- Parámetros del Sistema
INSERT INTO sar_configuracion.parametro_sistema (codigo, valor, descripcion) VALUES
('TRIBUTANET_URL',        'https://shacienda.qroo.gob.mx/tributanet/',                                                                          'URL base del portal Tributanet de Quintana Roo para la Fase A (Generación)'),
('TRIBUTANET_RPP_URL',    'https://shacienda.qroo.gob.mx/tributanet/rpp/dec_rpp_control.php?tipo_declaracion=1',                                 'URL directa al formulario de pago de derechos RPP de Tributanet (Fase A)'),
('SATQ_URL',              'https://paperless.sefiplan.qroo.gob.mx/',                                                                            'URL del portal SATQ para la Fase C (Consulta y Facturación/Timbrado)'),
('HEARTBEAT_INTERVAL',    '60',                                                                                                                  'Intervalo en segundos para enviar la señal de vida de sesión operativa (Heartbeat)'),
('TAMANO_LOTE',           '299',                                                                                                                 'Cantidad máxima de referencias agrupadas en un lote de control documental'),
('TAMANO_LOTE_SOLICITUD', '2000',                                                                                                                'Cantidad máxima de referencias asignadas a una solicitud individual para procesamiento del bot'),
('REINTENTOS_AUTOMATICOS','3',                                                                                                                   'Cantidad de intentos de reintento del bot ante fallas de red temporales'),
('RUTA_DERECHOS',         'T:\\DERECHOS',                                                                                                       'Ruta base por defecto donde se guardarán las boletas y facturas de los bots');

-- Municipios de Quintana Roo (Códigos de Portal Tributanet)
INSERT INTO sar_catalogo.municipio (codigo_portal, nombre) VALUES
('01', 'OTHON P. BLANCO'),
('02', 'BENITO JUAREZ'),
('03', 'COZUMEL'),
('04', 'ISLA MUJERES'),
('05', 'FELIPE CARRILLO PUERTO'),
('06', 'JOSE MARIA MORELOS'),
('07', 'LAZARO CARDENAS'),
('08', 'PLAYA DEL CARMEN'),
('09', 'TULUM'),
('00', 'CENTRAL'),
('10', 'BACALAR'),
('11', 'PUERTO MORELOS');

-- Delegaciones del RPP (Mapeadas a su respectivo Municipio ID)
-- 1: OTHON P. BLANCO, 2: BENITO JUAREZ, 8: PLAYA DEL CARMEN, 3: COZUMEL
INSERT INTO sar_catalogo.delegacion (municipio_id, codigo_portal, nombre) VALUES
(1, 'Delegación Chetumal (Othon p. Blanco, Carrillo Puerto, Jose Maria Morelos y Bacalar)', 'CHETUMAL'),
(2, 'Delegación Cancun (Benito Juarez, Isla Mujeres y Lazaro cardenas)',                    'CANCUN'),
(8, 'Delegación Playa del Carmen (Playa del Carmen y Tulum)',                               'PLAYA DEL CARMEN'),
(3, 'Delegación Cozumel',                                                                   'COZUMEL');

-- Conceptos de Cobro del RPP
INSERT INTO sar_catalogo.concepto (codigo_portal, nombre, alias) VALUES
('132-1 Análisis y calificación de documentos que contengan actos inscribibles-CT-65.00-117.31-',                                                                                         '1. Análisis y calificación de documentos', 'ANA'),
('137-3 Por solicitud de asiento de presentación de primer aviso preventivo con vigencia de 30 días o segundo aviso preventivo con vigencia de 90 días.-CT-12.00-117.31-',                '2. Primer o Segundo Aviso Preventivo',    'AVI'),
('141-5 Expedición de certificados de información o datos que obren en el sistema de registro-CT-5.00-117.31-',                                                                           '3. Certificados / CLG',                   'CLG');

-- Semilla de Notarías de prueba
INSERT INTO sar_catalogo.notaria (nombre) VALUES
('Notaría 12'), ('Notaría 15'), ('Notaría 5')
ON CONFLICT (nombre) DO NOTHING;

-- Localizadores del Portal Tributanet (Pantalla de Acceso RPP)
INSERT INTO sar_configuracion.localizador_portal (nombre_clave, label_visible, estrategia_selector, valor_selector, descripcion, portal) VALUES
('ddlMunicipio',               'Municipio',                                   'CSS',   'select[name="claveMunicipio"]',                                    'Selector del municipio en el formulario de acceso de Tributanet RPP',         'SAR'),
('txtRFC',                     'Registro Federal de Contribuyentes (RFC)',    'CSS',   'input[name="RFC"]',                                                'Input para capturar el RFC en el formulario de acceso de Tributanet RPP',     'SAR'),
('btnEnviar',                  'Enviar',                                      'CSS',   'input[type="submit"]',                                             'Botón para enviar el formulario de acceso de Tributanet RPP',                 'SAR'),
('txtNombre',                  'Apellido Paterno, Materno, Nombre(s)',        'CSS',   'input#Nombre',                                                     'Campo para Razón Social / Nombre en el formulario RPP',                      'SAR'),
('txtRfcReadOnly',             'RFC (Solo lectura)',                          'CSS',   'input#RFC',                                                        'Campo de RFC autocompletado en el formulario RPP',                           'SAR'),
('txtCalle',                   'Calle (Cruce o Numeración)',                  'CSS',   'input#Calle',                                                      'Campo para la calle del RFC en el formulario RPP',                           'SAR'),
('txtColonia',                 'Colonia',                                     'CSS',   'input#Colonia',                                                    'Campo para la colonia del RFC en el formulario RPP',                         'SAR'),
('txtNumeroExterior',          'No. Exterior',                                'CSS',   'input#Numero_Exterior',                                            'Campo para número exterior en el formulario RPP',                            'SAR'),
('txtNumeroInterior',          'No. Interior',                                'CSS',   'input#Numero_Interior',                                            'Campo para número interior en el formulario RPP',                            'SAR'),
('txtCodigoPostal',            'Código Postal',                               'CSS',   'input#Codigo_Postal',                                              'Campo para el código postal del RFC en el formulario RPP',                   'SAR'),
('txtLocalidad',               'Localidad',                                   'CSS',   'input#Localidad',                                                  'Campo para la localidad en el formulario RPP',                               'SAR'),
('txtMunicipioRfc',            'Municipio del RFC',                           'CSS',   'input#mun',                                                        'Campo para el municipio del RFC en el formulario principal RPP',              'SAR'),
('txtEstadoRfc',               'Estado del RFC',                              'CSS',   'input#Estado',                                                     'Campo para la entidad federativa / estado del RFC en el formulario principal RPP', 'SAR'),
('ddlDelegacion',              'Delegación',                                  'CSS',   'select[name="Delegacion"]',                                        'Selector de delegación física para el trámite RPP',                          'SAR'),
('ddlConcepto',                'Concepto',                                    'CSS',   'select#conceptos',                                                 'Selector de conceptos de cobro RPP',                                         'SAR'),
('btnAgregarConcepto',         'Agregar',                                     'CSS',   'input#agregar',                                                    'Botón para agregar el concepto seleccionado a la grilla RPP',                'SAR'),
('btnGenerarBoleta',           'Generar',                                     'CSS',   'input#generar',                                                    'Botón para finalizar y generar la boleta de pago RPP',                       'SAR'),
('lblBoletaReferencia',        'Referencia de la Boleta',                     'XPATH', '//b[contains(text(), "REFERENCIA")]',                              'Elemento que contiene los 17 dígitos de la referencia de pago',              'SAR'),
('lblBoletaFechaAlta',         'Fecha de Alta de la Boleta',                  'CSS',   'a.datomostrar',                                                    'Elemento que contiene la fecha y hora de generación de la boleta',           'SAR'),
('lblBoletaImporte',           'Importe de la Boleta',                        'XPATH', '//b[contains(text(), "IMPORTE")]',                                 'Elemento que contiene el monto a pagar de la boleta',                        'SAR'),
('lblBoletaFechaLimite',       'Fecha Límite de la Boleta',                   'XPATH', '//font[contains(text(), "FECHA LIMITE")]',                         'Elemento que contiene la fecha de vencimiento de la referencia',             'SAR'),
('btnImprimirBoleta',          'Imprimir',                                    'CSS',   'input[name="Imprimir"]',                                           'Botón para abrir el diálogo de impresión de la boleta',                     'SAR'),
('input_referencia',           'Campo Referencia (Consulta)',                 'CSS',   'input#Referencia',                                                 'Campo para ingresar la referencia a consultar y facturar',                   'SAR'),
('input_rfc',                  'Campo RFC (Consulta)',                        'CSS',   'input#RFC',                                                        'Campo para ingresar el RFC en la consulta de facturación',                   'SAR'),
('btn_buscar',                 'Botón Buscar Referencia',                     'CSS',   'button[type="submit"]',                                            'Botón para buscar la referencia a facturar',                                 'SAR'),
('btn_generar_cfdi',           'Botón Generar CFDI',                          'CSS',   'button:has-text("Generar CFDI"), a:has-text("Generar CFDI")',       'Botón para ingresar al formulario de timbrado de CFDI',                     'SAR'),
('input_nombre_receptor',      'Nombre Receptor (Razón Social)',              'CSS',   'input#NombreReceptor',                                             'Campo para ingresar la razón social en el timbrado',                        'SAR'),
('input_domicilio_fiscal_receptor', 'CP Receptor',                           'CSS',   'input#DomicilioFiscalReceptor',                                    'Campo para ingresar el código postal del receptor en el timbrado',          'SAR'),
('btn_timbrar',                'Botón Timbrar CFDI',                          'CSS',   'button#btnTimbrar',                                                'Botón final para timbrar el CFDI',                                          'SAR'),
('btn_pdf',                    'Botón Descargar PDF Factura',                 'CSS',   'button:has-text("PDF"), a:has-text("PDF")',                         'Botón para descargar el PDF de la factura generada',                        'SAR'),
('btn_salir',                  'Botón Salir Portal Factura',                  'CSS',   'button:has-text("Salir"), a.btn.btn-default[href="./"], a:has-text("Salir")', 'Botón para salir de la consulta y regresar al inicio', 'SAR');

-- ===========================================================================
-- SEMILLA DE SEGURIDAD (RBAC)
-- ===========================================================================

-- Roles
INSERT INTO sar_seguridad.rol (codigo, nombre, activo) VALUES
('ADMINISTRADOR', 'Administrador General del Sistema', TRUE),
('OPERADOR',      'Operador de Control y Scrapers',    TRUE);

-- Módulos
INSERT INTO sar_seguridad.modulo (codigo, nombre, descripcion) VALUES
('DASHBOARD',     'Tablero Principal',           'Módulo de métricas y resumen operativo'),
('ORDENES',       'Órdenes de Generación',       'Módulo de creación y control de requerimientos masivos'),
('SOLICITUDES',   'Solicitudes del Bot',         'Módulo de distribución y ejecución de solicitudes de scraping'),
('REFERENCIAS',   'Referencias y Facturas',      'Módulo de consulta, descarga y asignación de referencias/facturas'),
('CATALOGOS',     'Catálogos del Sistema',       'Módulo de mantenimiento de RFCs, conceptos y localizadores'),
('SEGURIDAD',     'Control de Acceso (RBAC)',    'Módulo de administración de usuarios, roles y permisos'),
('CONFIGURACION', 'Configuración General',       'Módulo de parámetros del sistema y localizadores');

-- Acciones
INSERT INTO sar_seguridad.accion (codigo, nombre, descripcion) VALUES
('CREAR',    'Crear',               'Permite registrar nuevos elementos'),
('LEER',     'Leer / Consultar',    'Permite visualizar y listar registros'),
('EDITAR',   'Editar / Modificar',  'Permite actualizar registros existentes'),
('ELIMINAR', 'Eliminar / Desactivar','Permite remover o desactivar registros'),
('ASIGNAR',  'Asignar',            'Permite asignar solicitudes y facturas a usuarios'),
('EJECUTAR', 'Ejecutar',           'Permite iniciar y controlar procesos del Bot (Playwright)');

-- Generar todos los Permisos (Intersección Módulo x Acción)
INSERT INTO sar_seguridad.permiso (modulo_id, accion_id, activo)
SELECT m.modulo_id, a.accion_id, TRUE
FROM sar_seguridad.modulo m
CROSS JOIN sar_seguridad.accion a;

-- Rol ADMINISTRADOR recibe TODOS los permisos
INSERT INTO sar_seguridad.rol_permiso (rol_id, permiso_id)
SELECT (SELECT rol_id FROM sar_seguridad.rol WHERE codigo = 'ADMINISTRADOR'), permiso_id
FROM sar_seguridad.permiso;

-- Rol OPERADOR recibe: LEER en todo, EJECUTAR en SOLICITUDES/REFERENCIAS, EDITAR en SOLICITUDES
INSERT INTO sar_seguridad.rol_permiso (rol_id, permiso_id)
SELECT (SELECT rol_id FROM sar_seguridad.rol WHERE codigo = 'OPERADOR'), p.permiso_id
FROM sar_seguridad.permiso p
JOIN sar_seguridad.modulo m ON p.modulo_id = m.modulo_id
JOIN sar_seguridad.accion a ON p.accion_id = a.accion_id
WHERE a.codigo = 'LEER'
   OR (m.codigo IN ('SOLICITUDES', 'REFERENCIAS') AND a.codigo = 'EJECUTAR')
   OR (m.codigo = 'SOLICITUDES' AND a.codigo = 'EDITAR');

-- Asociar Roles a Módulos de Aplicación
-- ADMINISTRADOR accede a todos
INSERT INTO sar_seguridad.rol_app_modulo (rol_id, app_modulo_id)
SELECT (SELECT rol_id FROM sar_seguridad.rol WHERE codigo = 'ADMINISTRADOR'), app_modulo_id
FROM sar_seguridad.app_modulo;

-- OPERADOR accede a CTRL_REF, BOT_FACE_A, BOT_C (no ADMIN)
INSERT INTO sar_seguridad.rol_app_modulo (rol_id, app_modulo_id)
SELECT (SELECT rol_id FROM sar_seguridad.rol WHERE codigo = 'OPERADOR'), app_modulo_id
FROM sar_seguridad.app_modulo
WHERE codigo IN ('CTRL_REF', 'BOT_FACE_A', 'BOT_C');

-- Usuario Administrador por Defecto
INSERT INTO sar_seguridad.usuario (username, nombre, correo, password_hash, activo) VALUES
('admin', 'Administrador General', 'admin@capturabot.com', '$argon2id$v=19$m=65536,t=3,p=4$anVzdGFzYWx0YnV0c2VjdXJl$placeholderhashforadmin123', TRUE);

INSERT INTO sar_seguridad.usuario_rol (usuario_id, rol_id) VALUES
((SELECT usuario_id FROM sar_seguridad.usuario WHERE username = 'admin'),
 (SELECT rol_id FROM sar_seguridad.rol WHERE codigo = 'ADMINISTRADOR'));

-- Eventos Críticos del Sistema
INSERT INTO sar_catalogo.evento_sistema (codigo, descripcion) VALUES
('CREAR_ORDEN',         'Creación de nueva orden de generación masiva'),
('PROCESAR_SOLICITUD',  'Inicio de procesamiento de solicitud de scraping por un worker'),
('GENERAR_REFERENCIA',  'Generación de una referencia de pago individual en Tributanet'),
('AUTORIZAR_REFERENCIA','Autorización / verificación de pago de una referencia'),
('FACTURAR_REFERENCIA', 'Generación y descarga de la factura CFDI (XML/PDF)'),
('ASIGNAR_FACTURA',     'Asignación de factura individual o masiva a un colaborador'),
('MODIFICAR_CATALOGO',  'Actualización de datos en catálogos del sistema (RFCs, localizadores, etc.)'),
('LOGIN_EXITOSO',       'Inicio de sesión de usuario en la aplicación'),
('LOGOUT',              'Cierre de sesión de usuario en la aplicación'),
('ERROR_CRITICO',       'Registro de un error crítico de ejecución o fallo del bot');

-- Estados del Sistema Estandarizados
INSERT INTO sar_catalogo.estado_sistema (entidad, codigo, descripcion) VALUES
('orden_generacion', 'ABIERTA',               'Orden abierta para edición'),
('orden_generacion', 'COMPLETADA',             'Orden con todas las referencias generadas'),
('orden_generacion', 'AUTORIZADA',             'Orden con todas las referencias autorizadas'),
('orden_generacion', 'RECHAZADA',              'Orden con todas las referencias rechazadas'),
('orden_generacion', 'CANCELADA',              'Orden cancelada'),
('grupo_referencia', 'PENDIENTE',              'Grupo pendiente de procesamiento'),
('grupo_referencia', 'COMPLETADO',             'Grupo completamente generado'),
('grupo_referencia', 'AUTORIZADO',             'Grupo completamente autorizado'),
('grupo_referencia', 'RECHAZADO',              'Grupo completamente rechazado'),
('grupo_referencia', 'AUTORIZACION_PARCIAL',   'Grupo con autorización parcial'),
('grupo_referencia', 'CANCELADO',              'Grupo cancelado'),
('solicitud',        'PENDIENTE',              'Solicitud pendiente de procesamiento por bot'),
('solicitud',        'PROCESANDO',             'Solicitud siendo procesada por bot'),
('solicitud',        'ASIGNADA',               'Solicitud asignada a operador/bot'),
('solicitud',        'COMPLETADA',             'Solicitud completada con éxito'),
('solicitud',        'AUTORIZADA',             'Solicitud autorizada de pago'),
('solicitud',        'RECHAZADA',              'Solicitud rechazada de pago'),
('solicitud',        'AUTORIZACION_PARCIAL',   'Solicitud con autorización parcial de pago'),
('solicitud',        'CANCELADA',              'Solicitud cancelada'),
('solicitud',        'ERROR',                  'Solicitud finalizada con error en bot'),
('solicitud',        'FACTURADA',              'Solicitud completamente facturada'),
('solicitud',        'FACTURADA_PARCIAL',      'Solicitud parcialmente facturada'),
('referencia',       'PENDIENTE',              'Referencia pendiente'),
('referencia',       'GENERADA',               'Referencia generada en Tributanet'),
('referencia',       'ASIGNADA',               'Referencia asignada a operador'),
('referencia',       'PENDIENTE_AUTORIZACION', 'Referencia pendiente de validación de pago'),
('referencia',       'AUTORIZADA',             'Referencia con pago verificado'),
('referencia',       'RECHAZADA',              'Referencia rechazada de pago'),
('referencia',       'EXPIRADA',               'Referencia vencida sin pago'),
('referencia',       'FACTURADA',              'Referencia facturada en SATQ'),
('referencia',       'ERROR',                  'Referencia con error en proceso'),
('referencia',       'ERROR_VALIDACION',       'Referencia con error de validación'),
('general',          'CANCELADO',              'Estado general cancelado')
ON CONFLICT (entidad, codigo) DO NOTHING;

-- ===========================================================================
-- AJUSTE DE SECUENCIAS (sincroniza IDs con los datos semilla insertados)
-- ===========================================================================

SELECT setval(COALESCE(pg_get_serial_sequence('sar_seguridad.usuario', 'usuario_id'), 'sar_seguridad.usuario_usuario_id_seq'), COALESCE((SELECT MAX(usuario_id) FROM sar_seguridad.usuario), 0) + 1, false);
SELECT setval(COALESCE(pg_get_serial_sequence('sar_seguridad.rol', 'rol_id'), 'sar_seguridad.rol_rol_id_seq'), COALESCE((SELECT MAX(rol_id) FROM sar_seguridad.rol), 0) + 1, false);
SELECT setval(COALESCE(pg_get_serial_sequence('sar_seguridad.app_modulo', 'app_modulo_id'), 'sar_seguridad.app_modulo_app_modulo_id_seq'), COALESCE((SELECT MAX(app_modulo_id) FROM sar_seguridad.app_modulo), 0) + 1, false);
SELECT setval(COALESCE(pg_get_serial_sequence('sar_seguridad.modulo', 'modulo_id'), 'sar_seguridad.modulo_modulo_id_seq'), COALESCE((SELECT MAX(modulo_id) FROM sar_seguridad.modulo), 0) + 1, false);
SELECT setval(COALESCE(pg_get_serial_sequence('sar_seguridad.accion', 'accion_id'), 'sar_seguridad.accion_accion_id_seq'), COALESCE((SELECT MAX(accion_id) FROM sar_seguridad.accion), 0) + 1, false);
SELECT setval(COALESCE(pg_get_serial_sequence('sar_seguridad.permiso', 'permiso_id'), 'sar_seguridad.permiso_permiso_id_seq'), COALESCE((SELECT MAX(permiso_id) FROM sar_seguridad.permiso), 0) + 1, false);
SELECT setval(COALESCE(pg_get_serial_sequence('sar_seguridad.sesion', 'sesion_id'), 'sar_seguridad.sesion_sesion_id_seq'), COALESCE((SELECT MAX(sesion_id) FROM sar_seguridad.sesion), 0) + 1, false);

SELECT setval(COALESCE(pg_get_serial_sequence('sar_catalogo.municipio', 'municipio_id'), 'sar_catalogo.municipio_municipio_id_seq'), COALESCE((SELECT MAX(municipio_id) FROM sar_catalogo.municipio), 0) + 1, false);
SELECT setval(COALESCE(pg_get_serial_sequence('sar_catalogo.delegacion', 'delegacion_id'), 'sar_catalogo.delegacion_delegacion_id_seq'), COALESCE((SELECT MAX(delegacion_id) FROM sar_catalogo.delegacion), 0) + 1, false);
SELECT setval(COALESCE(pg_get_serial_sequence('sar_catalogo.concepto', 'concepto_id'), 'sar_catalogo.concepto_concepto_id_seq'), COALESCE((SELECT MAX(concepto_id) FROM sar_catalogo.concepto), 0) + 1, false);
SELECT setval(COALESCE(pg_get_serial_sequence('sar_catalogo.rfc', 'rfc_id'), 'sar_catalogo.rfc_rfc_id_seq'), COALESCE((SELECT MAX(rfc_id) FROM sar_catalogo.rfc), 0) + 1, false);
SELECT setval(COALESCE(pg_get_serial_sequence('sar_catalogo.estado_sistema', 'estado_id'), 'sar_catalogo.estado_sistema_estado_id_seq'), COALESCE((SELECT MAX(estado_id) FROM sar_catalogo.estado_sistema), 0) + 1, false);
SELECT setval(COALESCE(pg_get_serial_sequence('sar_catalogo.evento_sistema', 'evento_id'), 'sar_catalogo.evento_sistema_evento_id_seq'), COALESCE((SELECT MAX(evento_id) FROM sar_catalogo.evento_sistema), 0) + 1, false);
SELECT setval(COALESCE(pg_get_serial_sequence('sar_catalogo.notaria', 'notaria_id'), 'sar_catalogo.notaria_notaria_id_seq'), COALESCE((SELECT MAX(notaria_id) FROM sar_catalogo.notaria), 0) + 1, false);
SELECT setval(COALESCE(pg_get_serial_sequence('sar_catalogo.colaborador', 'colaborador_id'), 'sar_catalogo.colaborador_colaborador_id_seq'), COALESCE((SELECT MAX(colaborador_id) FROM sar_catalogo.colaborador), 0) + 1, false);
SELECT setval(COALESCE(pg_get_serial_sequence('sar_catalogo.desarrollo', 'desarrollo_id'), 'sar_catalogo.desarrollo_desarrollo_id_seq'), COALESCE((SELECT MAX(desarrollo_id) FROM sar_catalogo.desarrollo), 0) + 1, false);
SELECT setval(COALESCE(pg_get_serial_sequence('sar_catalogo.desarrollo_empresa', 'desarrollo_empresa_id'), 'sar_catalogo.desarrollo_empresa_desarrollo_empresa_id_seq'), COALESCE((SELECT MAX(desarrollo_empresa_id) FROM sar_catalogo.desarrollo_empresa), 0) + 1, false);

SELECT setval(COALESCE(pg_get_serial_sequence('sar_produccion.orden_generacion', 'orden_id'), 'sar_produccion.orden_generacion_orden_id_seq'), COALESCE((SELECT MAX(orden_id) FROM sar_produccion.orden_generacion), 0) + 1, false);
SELECT setval(COALESCE(pg_get_serial_sequence('sar_produccion.grupo_referencia', 'grupo_id'), 'sar_produccion.grupo_referencia_grupo_id_seq'), COALESCE((SELECT MAX(grupo_id) FROM sar_produccion.grupo_referencia), 0) + 1, false);
SELECT setval(COALESCE(pg_get_serial_sequence('sar_produccion.solicitud', 'solicitud_id'), 'sar_produccion.solicitud_solicitud_id_seq'), COALESCE((SELECT MAX(solicitud_id) FROM sar_produccion.solicitud), 0) + 1, false);
SELECT setval(COALESCE(pg_get_serial_sequence('sar_produccion.referencia', 'referencia_id'), 'sar_produccion.referencia_referencia_id_seq'), COALESCE((SELECT MAX(referencia_id) FROM sar_produccion.referencia), 0) + 1, false);


SELECT setval(COALESCE(pg_get_serial_sequence('sar_archivo.archivo_pdf', 'archivo_id'), 'sar_archivo.archivo_pdf_archivo_id_seq'), COALESCE((SELECT MAX(archivo_id) FROM sar_archivo.archivo_pdf), 0) + 1, false);
SELECT setval(COALESCE(pg_get_serial_sequence('sar_archivo.factura', 'factura_id'), 'sar_archivo.factura_factura_id_seq'), COALESCE((SELECT MAX(factura_id) FROM sar_archivo.factura), 0) + 1, false);
SELECT setval(COALESCE(pg_get_serial_sequence('sar_archivo.lote_asignacion', 'lote_asignacion_id'), 'sar_archivo.lote_asignacion_lote_asignacion_id_seq'), COALESCE((SELECT MAX(lote_asignacion_id) FROM sar_archivo.lote_asignacion), 0) + 1, false);
SELECT setval(COALESCE(pg_get_serial_sequence('sar_archivo.lote_detalle', 'lote_detalle_id'), 'sar_archivo.lote_detalle_lote_detalle_id_seq'), COALESCE((SELECT MAX(lote_detalle_id) FROM sar_archivo.lote_detalle), 0) + 1, false);
SELECT setval(COALESCE(pg_get_serial_sequence('sar_archivo.ubicacion', 'ubicacion_id'), 'sar_archivo.ubicacion_ubicacion_id_seq'), COALESCE((SELECT MAX(ubicacion_id) FROM sar_archivo.ubicacion), 0) + 1, false);
SELECT setval(COALESCE(pg_get_serial_sequence('sar_archivo.asignacion_referencia', 'asignacion_referencia_id'), 'sar_archivo.asignacion_referencia_asignacion_referencia_id_seq'), COALESCE((SELECT MAX(asignacion_referencia_id) FROM sar_archivo.asignacion_referencia), 0) + 1, false);

SELECT setval(COALESCE(pg_get_serial_sequence('sar_auditoria.auditoria_login', 'login_id'), 'sar_auditoria.auditoria_login_login_id_seq'), COALESCE((SELECT MAX(login_id) FROM sar_auditoria.auditoria_login), 0) + 1, false);
SELECT setval(COALESCE(pg_get_serial_sequence('sar_auditoria.auditoria_evento', 'evento_auditoria_id'), 'sar_auditoria.auditoria_evento_evento_auditoria_id_seq'), COALESCE((SELECT MAX(evento_auditoria_id) FROM sar_auditoria.auditoria_evento), 0) + 1, false);
SELECT setval(COALESCE(pg_get_serial_sequence('sar_auditoria.auditoria_error', 'error_id'), 'sar_auditoria.auditoria_error_error_id_seq'), COALESCE((SELECT MAX(error_id) FROM sar_auditoria.auditoria_error), 0) + 1, false);

SELECT setval(COALESCE(pg_get_serial_sequence('sar_configuracion.parametro_sistema', 'parametro_id'), 'sar_configuracion.parametro_sistema_parametro_id_seq'), COALESCE((SELECT MAX(parametro_id) FROM sar_configuracion.parametro_sistema), 0) + 1, false);
SELECT setval(COALESCE(pg_get_serial_sequence('sar_configuracion.localizador_portal', 'localizador_id'), 'sar_configuracion.localizador_portal_localizador_id_seq'), COALESCE((SELECT MAX(localizador_id) FROM sar_configuracion.localizador_portal), 0) + 1, false);

SELECT setval(COALESCE(pg_get_serial_sequence('cancunbot_produccion.lote_folio', 'lote_id'), 'cancunbot_produccion.lote_folio_lote_id_seq'), COALESCE((SELECT MAX(lote_id) FROM cancunbot_produccion.lote_folio), 0) + 1, false);
SELECT setval(COALESCE(pg_get_serial_sequence('cancunbot_produccion.folio_cancun', 'folio_id'), 'cancunbot_produccion.folio_cancun_folio_id_seq'), COALESCE((SELECT MAX(folio_id) FROM cancunbot_produccion.folio_cancun), 0) + 1, false);
SELECT setval(COALESCE(pg_get_serial_sequence('cancunbot_produccion.recibo_cancun', 'recibo_id'), 'cancunbot_produccion.recibo_cancun_recibo_id_seq'), COALESCE((SELECT MAX(recibo_id) FROM cancunbot_produccion.recibo_cancun), 0) + 1, false);
SELECT setval(COALESCE(pg_get_serial_sequence('cancunbot_produccion.factura_cancun', 'factura_id'), 'cancunbot_produccion.factura_cancun_factura_id_seq'), COALESCE((SELECT MAX(factura_id) FROM cancunbot_produccion.factura_cancun), 0) + 1, false);

-- ===========================================================================
-- FIN DEL SCRIPT
-- ===========================================================================
